general.import = [
    "~/.config/alacritty/retrobox.toml",
]
[env]
term = "xterm-256color"
[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
size = 14

[window]
padding = {x = 8, y = 8}
